/-
Formalize the notion of a secret sharing scheme with a general access structure.
Show that the Shamir secret sharing scheme is an instance of this general scheme.
Extend linear secret sharing scheme to distributed matrix multiplication
-/

import Mathlib.Tactic
import Mathlib.Data.Fintype.Basic
import Mathlib.Probability.ProbabilityMassFunction.Basic
import Mathlib.Probability.Distributions.Uniform
import Mathlib.LinearAlgebra.Matrix.Rank
import Mathlib.LinearAlgebra.Lagrange

-- set_option maxHeartbeats 0
-- set_option maxRecDepth 4000
-- set_option synthInstance.maxHeartbeats 20000
-- set_option synthInstance.maxSize 128

set_option linter.style.longLine false
set_option linter.style.refine false
set_option linter.style.openClassical false
set_option linter.unusedSectionVars false
set_option linter.style.induction false

noncomputable section

/-
Definition of Access Structure.
-/
structure AccessStructure (n : ℕ) where
  auth : Set (Set (Fin n))
  h_monotone : ∀ {A B}, A ∈ auth → A ⊆ B → B ∈ auth

section AccessStructure

namespace AccessStructure

/-
Unauthorized sets = complement of authorized sets.
-/
def unauthorized {n : ℕ} (Γ : AccessStructure n) : Set (Set (Fin n)) :=
  {A | A ∉ Γ.auth}

/-
A set `A` is a minimal authorized set if it is authorized and no proper subset of `A` is authorized.
-/
def isMinimalAuthorized {n : ℕ} (Γ : AccessStructure n)
    (A : Set (Fin n)) : Prop :=
  A ∈ Γ.auth ∧ ∀ B : Set (Fin n), B ⊂ A → B ∉ Γ.auth

/-
The family Γ₀ of minimal authorized sets.
-/
def minimalAuthorized {n : ℕ} (Γ : AccessStructure n)
    : Set (Set (Fin n)) :=
  {A | isMinimalAuthorized Γ A}

/-
Every authorized set contains a minimal authorized subset.
-/
theorem auth_contains_minimal_auth {n : ℕ} (Γ : AccessStructure n) :
  ∀ B ∈ Γ.auth, ∃ A ∈ Γ.auth, isMinimalAuthorized Γ A ∧ A ⊆ B := by
    intro B hB;
    -- Apply the well-ordering principle to the set of authorized subsets of $B$.
    obtain ⟨A, hA⟩ : ∃ A ∈ {C : Set (Fin n) | C ∈ Γ.auth ∧ C ⊆ B}, ∀ C ∈ {C : Set (Fin n) | C ∈ Γ.auth ∧ C ⊆ B}, A.ncard ≤ C.ncard := by
      apply_rules [ Set.exists_min_image ];
      · exact Set.toFinite _;
      · exact ⟨ B, hB, Set.Subset.refl _ ⟩;
    use A;
    simp_all  [ isMinimalAuthorized ];
    intro C hC hC';
    have := hA.2 C hC' ( hC.1.trans hA.1.2 );
    exact this.not_gt ( Set.ncard_lt_ncard hC )

/-
A set `A` is a maximally unauthorized set if it is unauthorized and any proper superset of `A` is authorized.
-/
def isMaximallyUnauthorized {n : ℕ} (Γ : AccessStructure n)
    (A : Set (Fin n)) : Prop :=
  A ∉ Γ.auth ∧ ∀ B : Set (Fin n), A ⊂ B → B ∈ Γ.auth

/-
The family of maximally unauthorized sets.
-/
def maximallyUnauthorized {n : ℕ} (Γ : AccessStructure n)
    : Set (Set (Fin n)) :=
  {A | isMaximallyUnauthorized Γ A}

/-
The access structure generated by a collection of sets S consists of all supersets of the sets in S.
-/
def generatedAccessStructure {n : ℕ} (S : Set (Set (Fin n)))
   : Set (Set (Fin n)) :=
  upperClosure S

/-
An explicit statement of what `upper close` means.
-/
theorem mem_generatedAccessStructure_iff {n : ℕ} (S : Set (Set (Fin n))) (A : Set (Fin n)) :
    A ∈ generatedAccessStructure S ↔ ∃ B ∈ S, B ⊆ A := by
  simp [generatedAccessStructure, mem_upperClosure]

/-
The generated access structure contains the original collection of sets.
-/
theorem generatedAccessStructure_extensive {n : ℕ} (S : Set (Set (Fin n))) :
    S ⊆ generatedAccessStructure S := by
  exact fun x hx => ⟨ x, hx, le_rfl ⟩

/-
If S ⊆ T, then the access structure generated by T contains the subsets in the access structure generated by S.
-/
theorem generatedAccessStructure_mono {n : ℕ} {S T : Set (Set (Fin n))} (h : S ⊆ T) :
    generatedAccessStructure S ⊆ generatedAccessStructure T := by
  intros A hA
  obtain ⟨B, hB₁, hB₂⟩ := mem_upperClosure.mp hA
  have hB₃ : B ∈ T := h hB₁
  exact mem_upperClosure.mpr ⟨B, hB₃, hB₂⟩

/-
The generated access structure operation is idempotent.
-/
theorem generatedAccessStructure_idempotent {n : ℕ} (S : Set (Set (Fin n))) :
    generatedAccessStructure (generatedAccessStructure S) = generatedAccessStructure S := by
  simp_all [generatedAccessStructure ]

/-
The generated access structure operation is a closure operator.
-/
def generatedAccessStructureClosure (n : ℕ) : ClosureOperator (Set (Set (Fin n))) where
  toFun := generatedAccessStructure
  monotone' := fun _ _ h => generatedAccessStructure_mono h
  le_closure' := generatedAccessStructure_extensive
  idempotent' := generatedAccessStructure_idempotent

/-
The threshold access structure with threshold `t` out of `n` participants.
-/
def thresholdAccessStructure (n t : ℕ) : AccessStructure n where
  auth := generatedAccessStructure {A | A.ncard = t}
  h_monotone := by
    unfold generatedAccessStructure;
    simp [ upperClosure ];
    exact fun { A B } x hx hx' hx'' => ⟨ x, hx, hx'.trans hx'' ⟩

/-
A set is authorized in the threshold access structure iff its size is at least `t`.
-/
theorem threshold_auth_iff (n t : ℕ) (A : Set (Fin n)) :
  A ∈ (thresholdAccessStructure n t).auth ↔ t ≤ A.ncard := by
    constructor;
    · intro hA;
      -- Since $A$ is in the upper closure of the set of subsets
      -- with cardinality $t$, there exists some $B$ with $|B| = t$
      -- such that $B \subseteq A$.
      obtain ⟨B, hB_card, hB_subset⟩ : ∃ B : Set (Fin n), B.ncard = t ∧ B ⊆ A := by
        exact hA;
      exact hB_card ▸ Set.ncard_le_ncard hB_subset;
    · intro ht
      obtain ⟨B, hB⟩ : ∃ B : Set (Fin n), B ⊆ A ∧ B.ncard = t := by
        exact Set.exists_subset_card_eq ht;
      exact ⟨ B, hB.2, hB.1 ⟩


/-
All subsets of size t-1 are maximal unauthorized sets.
-/
theorem threshold_maximalUnauthorized_eq (n t : ℕ) (h_t : t > 0) (h_t_le_n : t ≤ n) :
  (thresholdAccessStructure n t).maximallyUnauthorized = {A | A.ncard = t - 1} := by
    ext A;
    constructor <;> intro hA;
    · have h_card : A.ncard < t := by
        exact lt_of_not_ge fun h => hA.1 <| by exact ( threshold_auth_iff n t A ) |>.2 h;
      have h_card : ∀ B : Set (Fin n), A ⊂ B → t ≤ B.ncard := by
        exact fun B hB => by have := hA.2 B hB; exact (threshold_auth_iff n t B).mp this;
      contrapose! h_card;
      -- Since $A$ is not maximal unauthorized, there exists an element $x \in \{0, 1, ..., n-1\} \setminus A$.
      obtain ⟨x, hx⟩ : ∃ x : Fin n, x ∉ A := by
        by_cases hA_univ : A = Set.univ;
        · simp_all  [ Set.ncard_univ ];
          linarith;
        · exact Set.nonempty_compl.2 hA_univ;
      refine' ⟨ Insert.insert x A, _, _ ⟩ <;> simp_all ;
      · exact ⟨ Set.subset_insert _ _, fun h => hx <| h <| Set.mem_insert _ _ ⟩;
      · rw [ Set.ncard_insert_of_notMem hx ] ; omega;
    · constructor;
      · exact fun h => by have := threshold_auth_iff n t A |>.1 h; linarith [ hA.symm, Nat.sub_add_cancel h_t ] ;
      · intro B hB
        have hB_card : B.ncard ≥ t := by
          have := Set.ncard_lt_ncard hB;
          grind;
        exact threshold_auth_iff n t B |>.2 hB_card

/-
The minimal authorized sets of the threshold access structure are exactly the sets of size `t`.
-/
theorem threshold_minimalAuthorized_eq (n t : ℕ) :
  (thresholdAccessStructure n t).minimalAuthorized = {A | A.ncard = t} := by
    -- To prove equality of sets, we show each set is a subset of the other.
    apply Set.ext
    intro A
    simp [minimalAuthorized, thresholdAccessStructure];
    constructor;
    · rintro ⟨ hA₁, hA₂ ⟩;
      obtain ⟨ B, hB₁, hB₂ ⟩ := hA₁;
      contrapose! hA₂;
      refine' ⟨ B, _, _ ⟩;
      · exact lt_of_le_of_ne hB₂ fun h => hA₂ <| h ▸ hB₁;
      · exact ⟨ B, hB₁, Set.Subset.refl _ ⟩;
    · intro hA
      constructor
      · exact (by
        exact ⟨ A, hA, Set.Subset.refl _ ⟩)
      · -- If B is a proper subset of A, then its cardinality is strictly less than t.
        intro B hB
        have hB_card : B.ncard < t := by
          exact hA ▸ Set.ncard_lt_ncard hB;
        simp [generatedAccessStructure];
        exact fun x hx hx' => hB_card.not_ge <| hx ▸ Set.ncard_le_ncard hx'

end AccessStructure  -- namespace

end AccessStructure  -- section




section SecretSharingScheme

/-
Data structure for Secret Sharing Scheme
-/
universe u v

/-
  A secret sharing scheme with `n` participants consist of the following data.

  `Secret` is a finite type and has size at least 2
  `Random` is another finite type that is nonempty
  The share of participant `i` has type `Share i`, for i = 0,1,..., n-1.
  We assume that `Share i` is a finite type for all `i`.
  share is a function that maps `Fin n` to `Type u`, representing the share of
  the `n` participants
  A `dealer` is a function that maps a pair of `Secret` and `Random` to the `n` shares.
-/
structure SecretSharingScheme (n : ℕ) where
  Secret : Type u
  Random : Type v
  [hSecret : Fintype Secret]
  hSecret_card : Fintype.card Secret ≥ 2
  Share : Fin n → Type u
  [hShare : ∀ i, Fintype (Share i)]
  [hRandom : Fintype Random]
  [hRandomNonempty : Nonempty Random]
  μ : PMF Random := PMF.uniformOfFintype Random
  dealer : Secret → Random → (∀ i, Share i)


namespace SecretSharingScheme

open AccessStructure

/-
Given a share s and a random string r, the restriction of Π(s,r) to A 
is denoted `shares_of_set`. We may also denote it by Π_A(s,r)

`shares_of_set` is a function that maps s, r, and A to
a function from A to the shares associated with the participants in A
-/
def shares_of_set {n : ℕ} (scheme : SecretSharingScheme n)
  (s : scheme.Secret) (r : scheme.Random) (A : Set (Fin n)) : (i : A) → scheme.Share i :=
  fun i => scheme.dealer s r i

/-! The type of **reconstruction algorithm** 

For every authorized subset `B`, the reconstruction algorithm is a function that
takes the shares in `B` as input and return a term of type `Secret`
-/
def ReconstructionAlgorithm {n : ℕ} (scheme : SecretSharingScheme n) (Γ : AccessStructure n) :=
  ∀ (B : Set (Fin n)), B ∈ Γ.auth → ((i : B) → scheme.Share i) → scheme.Secret

/-
Correctness means that for every authorized set B ∈ Γ, and secret s ∈ S, the participants in B can reconstruct the secret correctly with probability 1.
-/
def Correctness {n : ℕ} (S : SecretSharingScheme n) (Γ : AccessStructure n) (recon : ReconstructionAlgorithm S Γ) :=
  ∀ (s : S.Secret) (r : S.Random) (B : Set (Fin n)) (hB : B ∈ Γ.auth),
  recon B hB (shares_of_set S s r B) = s

/-
For every unauthorized set B ∉ Γ, the shares held by B reveal 
no information about the secret.

Fix an unauthorized set B. For each secret s, (shares_of_set S s r B ) with r random
gives a distribution on |B|-tuple of shares. Perfect security requires that
this distribution is the same for all secret s. The equation in the condition is
$$
\Pr(\Pi_T(s_1,r) = \langle s_j\rangle_{j\in T}) = 
\Pr(\Pi_T(s_2,r) = \langle s_j\rangle_{j\in T} )
$$
-/
def PerfectSecurity {n : ℕ} (S : SecretSharingScheme n) (Γ : AccessStructure n) :=
  ∀ (B : Set (Fin n)) (_hB : B ∉ Γ.auth) (s s' : S.Secret),
    (S.μ.map (fun r => shares_of_set S s r B )) =
    (S.μ.map (fun r => shares_of_set S s' r B))

/-
A structure representing a secret sharing scheme that realizes a given access structure Γ.
-/
structure RealizedSecretSharingScheme (n : ℕ) (Γ : AccessStructure n) extends SecretSharingScheme n where
  /-- The reconstruction algorithm for the scheme. -/
  recon : ReconstructionAlgorithm toSecretSharingScheme Γ
  /-- Proof of correctness: authorized sets can reconstruct the secret. -/
  h_correctness : Correctness toSecretSharingScheme Γ recon
  /-- Proof of perfect security: unauthorized sets learn nothing about the secret. -/
  h_security : PerfectSecurity toSecretSharingScheme Γ


/-
The size of secret is log(|S|).
-/
noncomputable def secret_size {n : ℕ} (scheme : SecretSharingScheme n) : ℝ :=
  letI := scheme.hSecret
  Real.log (Fintype.card scheme.Secret)

/-
The size of the share of participant i is log(|Si|).
-/
noncomputable def share_size {n : ℕ} (scheme : SecretSharingScheme n) (i : Fin n) : ℝ :=
  letI := scheme.hShare i
  Real.log (Fintype.card (scheme.Share i))

/-
The maximum share size is max_j log(|Sj|).
-/
noncomputable def max_share_size {n : ℕ} (scheme : SecretSharingScheme n) : ℝ :=
  letI := scheme.hShare
  (Finset.univ.image (fun i => share_size scheme i)).max.getD 0

/-
The Total share size is sum_j log(|Sj|).
-/
noncomputable def total_share_size {n : ℕ} (scheme : SecretSharingScheme n) : ℝ :=
  letI := scheme.hShare
  Finset.sum Finset.univ (fun i => share_size scheme i)

/-
The information ratio is max_j log(|Sj|) / log(|S|).
-/
noncomputable def information_ratio {n : ℕ} (scheme : SecretSharingScheme n) : ℝ :=
  (max_share_size scheme) / (secret_size scheme)


/-
To verify perfect security, we only need to verify the condition for maximally unauthorized set.
-/
theorem PerfectSecurity_iff_maximal {n : ℕ} (scheme : SecretSharingScheme n) (Γ : AccessStructure n) :
    PerfectSecurity scheme Γ ↔
    ∀ (T : Set (Fin n)), isMaximallyUnauthorized Γ T →
      ∀ (s1 s2 : scheme.Secret),
        (scheme.μ.map (fun r => shares_of_set scheme s1 r T)) =
        (scheme.μ.map (fun r => shares_of_set scheme s2 r T)) := by
          refine' ⟨ _, fun h => _ ⟩;
          · exact fun h T hT s1 s2 => h T hT.1 s1 s2
          · -- For any unauthorized set T, there exists a maximally unauthorized set T'
            -- such that T is a subset of T'.
            have h_max_unauthorized : ∀ T : Set (Fin n), T ∉ Γ.auth → ∃ T' : Set (Fin n),
                isMaximallyUnauthorized Γ T' ∧ T ⊆ T' := by
              intro T hT;
              -- Since $T$ is unauthorized, there exists a maximally
              -- unauthorized set $T'$ containing $T$.
              obtain ⟨T', hT'⟩ : ∃ T' : Set (Fin n), T ⊆ T' ∧ T' ∉ Γ.auth
                   ∧ ∀ B : Set (Fin n), T' ⊂ B → B ∈ Γ.auth := by
                have h_max : ∃ T' : Set (Fin n), T ⊆ T' ∧ T' ∉ Γ.auth
                   ∧ ∀ B : Set (Fin n), T' ⊂ B → B ∈ Γ.auth := by
                  have h_finite : Set.Finite {B : Set (Fin n) | T ⊆ B ∧ B ∉ Γ.auth} := by
                    exact Set.toFinite _
                  obtain ⟨T', hT'_max⟩ : ∃ T' ∈ {B : Set (Fin n) | T ⊆ B
                      ∧ B ∉ Γ.auth}, ∀ B ∈ {B : Set (Fin n) | T ⊆ B ∧ B ∉ Γ.auth}, T'.ncard ≥ B.ncard := by
                    apply_rules [ Set.exists_max_image ]
                    exact ⟨ T, Set.Subset.refl _, hT ⟩
                  exact ⟨ T', hT'_max.1.1, hT'_max.1.2, fun B hB => Classical.not_not.1 fun hB' => not_lt_of_ge
                    ( hT'_max.2 B ⟨ hT'_max.1.1.trans hB.1, hB' ⟩ ) ( Set.ncard_lt_ncard hB ) ⟩
                exact h_max
              exact ⟨ T', ⟨ hT'.2.1, hT'.2.2 ⟩, hT'.1 ⟩
            -- By combining the results from h_max_unauthorized and h, we can conclude the proof.
            intros T hT s1 s2
            obtain ⟨T', hT', hT'_superset⟩ := h_max_unauthorized T hT
            have h_eq : (scheme.μ.map (fun r => shares_of_set scheme s1 r T'))
               = (scheme.μ.map (fun r => shares_of_set scheme s2 r T')) := by
              exact h T' hT' s1 s2
            convert congr_arg ( fun f => f.map ( fun x => fun i : T => x ⟨ i, hT'_superset i.2 ⟩ ) )
                h_eq using 1 <;>
              simp [ PMF.map ];
            · congr! 2
            · congr! 2

end SecretSharingScheme -- namespace

end SecretSharingScheme  -- section



section ShamirScheme

namespace ShamirScheme

open AccessStructure
open SecretSharingScheme
open BigOperators Finset Matrix Polynomial
open scoped Classical

/-
Definition of the polynomial used in Shamir's Secret Sharing Scheme.
-/
universe u

variable {F : Type*} [Field F] [Fintype F] [DecidableEq F]

/-- Shamir's secret sharing polynomial evaluation.
    s is the secret (constant term).
    m contains the t-1 random coefficients m_1, ..., m_{t-1}.
    z is the evaluation point. -/
def shamir_poly (t : ℕ) (s : F) (m : Fin (t - 1) → F) (z : F) : F :=
  s + ∑ j : Fin (t - 1), m j * z ^ (j.val + 1)


/-
The uniform distribution on the coefficients.
-/
noncomputable def uniform_coeffs (t : ℕ) : PMF (Fin (t - 1) → F) :=
  PMF.uniformOfFintype (Fin (t - 1) → F)


/-
The cardinality of a finite field is at least 2.
-/
theorem FiniteField.card_ge_two (F : Type*) [Field F] [Fintype F] : Fintype.card F ≥ 2 := by
  have h : 0 ≠ (1 : F) := zero_ne_one
  have h_card : Fintype.card F > 1 := Fintype.one_lt_card_iff_nontrivial.mpr inferInstance
  exact Nat.succ_le_of_lt h_card

/-- Shamir's Secret Sharing Scheme. -/
def shamirScheme (n t : ℕ) (hF : Fintype.card F ≥ 2)
    (x : Fin n → F)
    (_h_distinct : Function.Injective x)
    (_h_nonzero : ∀ i, x i ≠ 0) : SecretSharingScheme n where
  Secret := F
  Random := Fin (t - 1) → F
  hSecret := inferInstance
  hSecret_card := hF
  Share := fun _ => F
  hShare := fun _ => inferInstance
  hRandom := inferInstance
  hRandomNonempty := inferInstance
  μ := uniform_coeffs t
  dealer := fun s m i => shamir_poly t s m (x i)



theorem threshold_auth_iff (n t : ℕ) (B : Set (Fin n)) :
    B ∈ (thresholdAccessStructure n t).auth ↔ t ≤ B.ncard := by
  -- By definition of the threshold access structure, B is authorized if and only if there exists a subset A with exactly t elements such that A is a subset of B.
  simp [thresholdAccessStructure, generatedAccessStructure];
  -- If there exists a subset $a$ of $B$ with cardinality $t$, then clearly $t \leq B.ncard$.
  apply Iff.intro;
  · rintro ⟨ a, ha₁, ha₂ ⟩ ; exact ha₁ ▸ Set.ncard_le_ncard ha₂;
  · -- If B has at least t elements, then we can choose a subset a of B with exactly t elements.
    intro ht
    obtain ⟨a, ha⟩ : ∃ a : Finset (Fin n), a.card = t ∧ ∀ x ∈ a, x ∈ B := by
      have := Set.exists_subset_card_eq ht;
      obtain ⟨ a, ha₁, ha₂ ⟩ := this; exact ⟨ a.toFinset, by simpa [ Set.ncard_eq_toFinset_card' ] using ha₂, fun x hx => ha₁ <| by simpa using hx ⟩ ;
    exact ⟨ a, by simpa [ Set.ncard_eq_toFinset_card' ] using ha.1, fun x hx => ha.2 x hx ⟩

noncomputable def shamir_reconstruction (n t : ℕ) (x : Fin n → F)
    (B : Set (Fin n)) (hB : B ∈ (thresholdAccessStructure n t).auth)
    (shares : (i : B) → F) : F :=
  let h_card : t ≤ B.ncard := (threshold_auth_iff n t B).mp hB
  let S := Classical.choose (Set.exists_subset_card_eq h_card)
  let S_finset := S.toFinset
  let shares_ext : Fin n → F := fun i =>
    if h : i ∈ B then shares ⟨i, h⟩ else 0
  ((Lagrange.interpolate S_finset x) shares_ext).eval 0

def shamir_linear_map (n t : ℕ) (x : Fin n → F) (B : Set (Fin n)) (r : Fin (t - 1) → F) : B → F :=
  fun i => ∑ j : Fin (t - 1), r j * (x i) ^ (j.val + 1)

lemma shamir_linear_map_surjective (n t : ℕ) (x : Fin n → F) (h_distinct : Function.Injective x)
    (h_nonzero : ∀ i, x i ≠ 0) (B : Set (Fin n)) (hB : B.ncard < t) :
    Function.Surjective (shamir_linear_map n t x B) := by
  -- Since $B$ has fewer than $t$ elements,
  -- the system of equations given by the evaluations is underdetermined,
  -- and thus there exists a $p$ such that $p(i) = s_i$ for each $i \in B$.
  have h_undetermined : ∀ (s : B → F), ∃ p : Fin (t - 1) → F, ∀ i : B, ∑ j : Fin (t - 1), p j * x i ^ (j.val + 1) = s i := by
    -- Since the Vandermonde matrix is invertible,
    -- the system of equations has a unique solution for any right-hand side.
    have h_vandermonde_inv : ∀ (s : B → F), ∃ p : Fin (B.ncard) → F, ∀ i : B, ∑ j : Fin (B.ncard), p j * x i ^ (j.val + 1) = s i := by
      -- Since the x_i are distinct, the Vandermonde matrix is invertible,
      -- so the system has a unique solution.
      have h_vandermonde_inv : ∀ (s : B → F), ∃ p : Fin (B.ncard) → F,
          ∀ i : B, ∑ j : Fin (B.ncard), p j * x i ^ (j.val) = s i := by
        intro s;
        -- Since $B$ is a finite set, we can choose a bijection $f : Fin B.ncard ≃ B$.
        obtain ⟨f, hf⟩ : ∃ f : Fin B.ncard ≃ B, True := by
          simp +zetaDelta at *;
          exact ⟨ Fintype.equivOfCardEq <| by simp  [ Set.ncard_eq_toFinset_card' ] ⟩;
        -- Since $B$ is a finite set, we can choose a bijection $f : Fin B.ncard ≃ B$ and use it to construct the polynomial $p$.
        obtain ⟨p, hp⟩ : ∃ p : Fin B.ncard → F, ∀ i : Fin B.ncard, ∑ j : Fin B.ncard, p j * x (f i) ^ (j.val) = s (f i) := by
          have h_vandermonde_inv : Matrix.det (Matrix.of (fun i j : Fin B.ncard => x (f i) ^ (j.val))) ≠ 0 := by
            erw [ Matrix.det_vandermonde ];
            simp  [ Finset.prod_eq_zero_iff, sub_eq_zero, h_distinct.eq_iff ];
            exact fun i j hij => fun h => hij.ne <| f.injective <| Subtype.ext h.symm;
          have h_vandermonde_inv : ∀ (b : Fin B.ncard → F), ∃ p : Fin B.ncard → F, Matrix.mulVec (Matrix.of (fun i j : Fin B.ncard => x (f i) ^ (j.val))) p = b := by
            exact fun b => ⟨ Matrix.mulVec ( Matrix.of ( fun i j : Fin B.ncard => x ( f i ) ^ ( j.val ) ) ) ⁻¹ b, by simp  [ h_vandermonde_inv, isUnit_iff_ne_zero ] ⟩;
          exact Exists.elim ( h_vandermonde_inv fun i => s ( f i ) ) fun p hp => ⟨ p, fun i => by simpa [ Matrix.mulVec, dotProduct, mul_comm ] using congr_fun hp i ⟩;
        exact ⟨ p, fun i => by simpa using hp ( f.symm i ) |> fun h => by simpa [ f.apply_symm_apply ] using h ⟩;
      intro s
      obtain ⟨p, hp⟩ := h_vandermonde_inv (fun i => s i / x i);
      use p;
      simp_all  [ pow_succ, ← mul_assoc, ← Finset.sum_mul _ _ _ ];
    intro s
    obtain ⟨p, hp⟩ := h_vandermonde_inv s;
    use fun j => if hj : j.val < B.ncard then p ⟨ j.val, hj ⟩ else 0;
    intro i;
    rw [ ← hp i ] ;
    rw [ ← Finset.sum_subset ( Finset.subset_univ ( Finset.image ( fun j : Fin B.ncard => ⟨ j.val, by linarith [ Fin.is_lt j, Nat.sub_add_cancel ( show 1 ≤ t from Nat.succ_le_of_lt ( pos_of_gt hB ) ) ] ⟩ : Fin B.ncard → Fin ( t - 1 ) ) Finset.univ ) ) ] ;
    · -- rw [ Finset.sum_image ] <;>
      --simp [ Fin.ext_iff ];
      simp only [dite_mul, zero_mul, coe_univ, Fin.ext_iff, implies_true, Set.injOn_of_eq_iff_eq, sum_image, Fin.is_lt,
    ↓reduceDIte, Fin.eta]
    simp +contextual [ Fin.ext_iff ];
      exact fun j hj h => False.elim <| hj ⟨ j, h ⟩ rfl;
  exact fun s => by obtain ⟨ p, hp ⟩ := h_undetermined s; exact ⟨ p, funext fun i => by simpa [ shamir_poly ] using hp i ⟩ ;

lemma map_uniform_of_fiber_card_eq {A B : Type u} [Fintype A] [Fintype B] [Nonempty A] [Nonempty B]
    (f : A → B) (k : ℕ) (h_fibers : ∀ y : B, Fintype.card {x // f x = y} = k) :
    PMF.map f (PMF.uniformOfFintype A) = PMF.uniformOfFintype B := by
  -- By definition of PMF.map, we have:
  ext y
  simp [PMF.map];
  -- Since there are $k$ elements in $A$ that map to $y$, the sum of the probabilities of these elements is $k \cdot \frac{1}{|A|} = \frac{k}{|A|}$.
  have h_sum : ∑' a : A, (if y = f a then (1 : ENNReal) / (Fintype.card A) else 0) = (k : ENNReal) / (Fintype.card A) := by
    rw [ tsum_eq_sum ];
    any_goals exact Finset.univ.filter fun x => f x = y;
    · simp  [ ← h_fibers y, Fintype.card_subtype ];
      rw [ Finset.sum_congr rfl fun x hx => if_pos <| Eq.symm <| Finset.mem_filter.mp hx |>.2 ] ; simp  [ div_eq_mul_inv ];
    · aesop;
  -- Since there are $k$ elements in $A$ that map to each $y$, the total number of elements in $A$ is $k \cdot |B|$.
  have h_card_A : Fintype.card A = k * Fintype.card B := by
    have h_card_A : Fintype.card A = ∑ y : B, Fintype.card { x : A // f x = y } := by
      simp  only [Fintype.card_subtype];
      simp  only [Finset.card_filter];
      rw [ Finset.sum_comm ] ; simp ;
    simp  [ h_card_A, h_fibers, mul_comm ];
  by_cases hk : k = 0 <;> simp_all  [ division_def ];
  rw [←  ENNReal.toReal_eq_toReal_iff' ] <;> norm_num [ hk ];
  · exact mul_div_cancel₀ _ ( Nat.cast_ne_zero.mpr hk );
  · simp  [ ENNReal.mul_eq_top, hk ]

lemma shamir_fiber_card_constant (n t : ℕ) (x : Fin n → F) (h_distinct : Function.Injective x)
    (h_nonzero : ∀ i, x i ≠ 0) (B : Set (Fin n)) (hB : B.ncard < t) (s : F) :
    ∃ k, ∀ y : B → F, Fintype.card { m : Fin (t - 1) → F // (fun i : B => shamir_poly t s m (x i)) = y } = k := by
  use Fintype.card { m : Fin (t - 1) → F // (fun i : B => shamir_poly t s m (x i)) = (fun i : B => shamir_poly t s 0 (x i)) };
  intro y
  have h_fibers : ∀ y : B → F, ∃ m₀ : Fin (t - 1) → F, (fun i : B => shamir_poly t s m₀ (x i)) = y := by
    intro y
    obtain ⟨m₀, hm₀⟩ : ∃ m₀ : Fin (t - 1) → F, (fun i : B => ∑ j : Fin (t - 1), m₀ j * (x i) ^ (j.val + 1)) = fun i : B => y i - s := by
      have := shamir_linear_map_surjective n t x h_distinct h_nonzero B hB;
      exact this _;
    use m₀; simp_all  [ funext_iff, shamir_poly ] ;
  obtain ⟨ m₀, rfl ⟩ := h_fibers y;
  refine' Fintype.card_congr _;
  refine' ⟨ fun m => ⟨ m.val - m₀, _ ⟩, fun m => ⟨ m.val + m₀, _ ⟩, fun m => _, fun m => _ ⟩ <;> simp_all  [ funext_iff];
  · intro i hi; have := congr_fun m.2 ⟨ i, hi ⟩ ; simp_all  [ shamir_poly ] ;
    simp_all  [ sub_mul ];
  · intro i hi; have := congr_fun m.2 ⟨ i, hi ⟩ ; simp_all  [ shamir_poly ] ;
    simp_all  [ add_mul, Finset.sum_add_distrib ]

lemma shamir_shares_uniform (n t : ℕ) (_hF : Fintype.card F ≥ 2)
    (x : Fin n → F) (h_distinct : Function.Injective x) (h_nonzero : ∀ i, x i ≠ 0)
    (B : Set (Fin n)) (hB : B.ncard < t) (s : F) :
    PMF.map (fun r => fun (i : B) => shamir_poly t s r (x i)) (uniform_coeffs t) = PMF.uniformOfFintype (B → F) := by
  apply map_uniform_of_fiber_card_eq;
  convert shamir_fiber_card_constant n t x h_distinct h_nonzero B hB s |> Classical.choose_spec

theorem shamir_perfect_security (n t : ℕ) (hF : Fintype.card F ≥ 2)
    (x : Fin n → F) (h_distinct : Function.Injective x) (h_nonzero : ∀ i, x i ≠ 0) (_ht : t > 0) (_htn : t ≤ n) :
    PerfectSecurity (shamirScheme n t hF x h_distinct h_nonzero)
      (thresholdAccessStructure n t) := by
        intro B hB s s';
        have h_uniform : ∀ s : F, PMF.map (fun r : Fin (t - 1) → F => fun (i : B) 
          => shamir_poly t s r (x i)) 
          (uniform_coeffs t) = PMF.uniformOfFintype (B → F) := by
          apply shamir_shares_uniform;
          · exact hF;
          · assumption;
          · assumption;
          · exact lt_of_not_ge fun h => hB <| threshold_auth_iff n t B |>.2 h;
        exact h_uniform s ▸ h_uniform s' ▸ rfl

-- alternate description of shamir_poly using Polynomial type
def shamir_polynomial (t : ℕ) (s : F) (m : Fin (t - 1) → F) : Polynomial F :=
  Polynomial.C s + ∑ i : Fin (t - 1), Polynomial.C (m i) * Polynomial.X ^ (i.val + 1)

-- shamir_poly and shamir_polynomial have the same mathematical meaning
lemma shamir_polynomial_eval (t : ℕ) (s : F) (m : Fin (t - 1) → F) (z : F) :
    (shamir_polynomial t s m).eval z = shamir_poly t s m z := by
      -- By definition of polynomial evaluation, we can expand the left-hand side.
      simp [shamir_polynomial, Polynomial.eval_finset_sum, Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_pow];
      -- By definition of polynomial evaluation, we can expand the left-hand side to match the right-hand side.
      simp [shamir_poly]

lemma shamir_polynomial_degree_le (t : ℕ) (s : F) (m : Fin (t - 1) → F) :
    (shamir_polynomial t s m).natDegree ≤ t - 1 := by
      -- The polynomial is constructed by adding a constant term s and a sum of terms m_i * x^(i+1). Each term in the sum is a monomial of degree i+1, where i ranges from 0 to t-2. The highest degree term here is when i is t-2, which gives x^(t-1). So the degree of the polynomial should be t-1.
      have h_deg : (shamir_polynomial t s m).natDegree ≤ Finset.sup (Finset.univ : Finset (Fin (t - 1))) (fun i => i.val + 1) := by
        -- The degree of the sum of polynomials is the maximum of their degrees.
        have h_deg_sum : (Finset.sum Finset.univ fun i => Polynomial.C (m i) * Polynomial.X ^ ((i : ℕ) + 1)).natDegree ≤ Finset.sup (Finset.univ : Finset (Fin (t - 1))) (fun i => (i : ℕ) + 1) := by
          refine' le_trans ( Polynomial.natDegree_sum_le _ _ ) ( Finset.sup_le _ );
          exact fun i _ => le_trans ( Polynomial.natDegree_C_mul_X_pow_le _ _ ) ( Finset.le_sup ( f := fun i : Fin ( t - 1 ) => ( i : ℕ ) + 1 ) ( Finset.mem_univ i ) );
        exact le_trans ( Polynomial.natDegree_add_le _ _ ) ( max_le ( by aesop ) h_deg_sum );
      exact h_deg.trans ( Finset.sup_le fun i _ => Nat.succ_le_of_lt i.2 )


lemma shamir_interpolation_correct (n t : ℕ) (_hF : Fintype.card F ≥ 2)
    (x : Fin n → F) (h_distinct : Function.Injective x) (_h_nonzero : ∀ i, x i ≠ 0)
    (s : F) (m : Fin (t - 1) → F)
    (B : Set (Fin n)) (hB : B ∈ (thresholdAccessStructure n t).auth) (ht : t ≠ 0) :
    let h_card : t ≤ B.ncard := (threshold_auth_iff n t B).mp hB
    let S := Classical.choose (Set.exists_subset_card_eq h_card)
    let S_finset := S.toFinset
    let shares : (i : B) → F := fun i => shamir_poly t s m (x i)
    let shares_ext : Fin n → F := fun i => if h : i ∈ B then shares ⟨i, h⟩ else 0
    (Lagrange.interpolate S_finset x) shares_ext = shamir_polynomial t s m := by
      refine' Polynomial.eq_of_degree_sub_lt_of_eval_finset_eq _ _ _;
      · exact Finset.image x ( Classical.choose ( Set.exists_subset_card_eq ( show t ≤ B.ncard from ( threshold_auth_iff n t B ).mp hB ) ) |> Set.toFinset );
      · refine' lt_of_le_of_lt ( Polynomial.degree_sub_le _ _ ) ( max_lt _ _ );
        · convert Lagrange.degree_interpolate_lt _ _;
          · rw [ Finset.card_image_of_injective _ h_distinct ];
          · exact h_distinct.injOn;
        · refine' lt_of_le_of_lt ( Polynomial.degree_le_natDegree ) _;
          rw [ Finset.card_image_of_injective _ h_distinct ];
          have := Classical.choose_spec ( Set.exists_subset_card_eq ( show t ≤ Set.ncard B from ( threshold_auth_iff n t B ).mp hB ) );
          simp_all  [ Set.ncard_eq_toFinset_card' ];
          exact lt_of_le_of_lt ( shamir_polynomial_degree_le t s m ) ( Nat.pred_lt ht );
      · simp;
        intro i hi; rw [ Polynomial.eval_finset_sum, Finset.sum_eq_single i ] <;> simp  [ Lagrange.basis ] ;
        · rw [ if_pos ( Classical.choose_spec ( Set.exists_subset_card_eq ( show t ≤ B.ncard from ( threshold_auth_iff n t B ).mp hB ) ) |>.1 hi ) ] ; simp  [ Polynomial.eval_prod, Lagrange.basisDivisor ] ;
          rw [ Finset.prod_eq_one fun j hj => by rw [ inv_mul_cancel₀ ] ; exact sub_ne_zero_of_ne <| h_distinct.ne <| by aesop ] ; simp  [ shamir_polynomial_eval ];
        · intro j hj hij hjB; rw [ Polynomial.eval_prod ] ; exact Or.inr ( Finset.prod_eq_zero ( Finset.mem_erase_of_ne_of_mem ( Ne.symm hij ) ( by aesop ) ) ( by simp  [ Lagrange.basisDivisor ] ) ) ;
        · exact fun h₁ h₂ => False.elim <| h₁ hi

-- Correctness of Shamir secret sharing scheme
theorem shamir_scheme_correctness (n t : ℕ) (hF : Fintype.card F ≥ 2)
    (x : Fin n → F) (h_distinct : Function.Injective x) (h_nonzero : ∀ i, x i ≠ 0) (ht : t ≠ 0) :
    Correctness (shamirScheme n t hF x h_distinct h_nonzero)
      (thresholdAccessStructure n t) (shamir_reconstruction n t x) := by
        -- By definition of Shamir's scheme, the polynomial is constructed such that evaluating it at 0 gives the secret.
        have h_poly_eval : ∀ (s : F) (m : Fin (t - 1) → F), (shamir_polynomial t s m).eval 0 = s := by
          -- By definition of Shamir's polynomial, evaluating it at 0 gives the secret.
          intros s m
          simp [shamir_polynomial];
          simp  [ Polynomial.eval_finset_sum ];
        intro s r B hB;
        convert h_poly_eval s r using 1;
        convert congr_arg ( Polynomial.eval 0 ) ( shamir_interpolation_correct n t hF x h_distinct h_nonzero s r B hB ht ) using 1


-- Shamir secret sharing scheme realizes threshold access structure
def shamirRealizedScheme (n t : ℕ) (hF : Fintype.card F ≥ 2)
    (x : Fin n → F) (h_distinct : Function.Injective x) (h_nonzero : ∀ i, x i ≠ 0)
    (ht : t > 0) (htn : t ≤ n)
  : RealizedSecretSharingScheme n (thresholdAccessStructure n t) := {
  shamirScheme n t hF x h_distinct h_nonzero with
  recon := shamir_reconstruction n t x
  h_correctness := shamir_scheme_correctness n t hF x h_distinct h_nonzero (ne_of_gt ht)
  h_security := shamir_perfect_security n t hF x h_distinct h_nonzero ht htn
}

end ShamirScheme  -- namespace

end ShamirScheme  --section






section DisjointAccessStructure

open AccessStructure

open BigOperators
open Classical 
variable {n : ℕ} {p : ℕ} [Fact p.Prime]


/--
A share is an optional value in ZMod p.
If the participant is not in any qualified set, it is none.
-/
def Share (p : ℕ) := Option (ZMod p)

/--
The validity of a sharing of a secret S with respect to the disjoint qualified sets Qs.
-/
def IsValidSharing (Qs : Set (Set (Fin n))) (S : ZMod p) (σ : Fin n → Share p) : Prop :=
  -- 1. Participants not in any Q ∈ Qs have no share.
  (∀ i, (∀ Q ∈ Qs, i ∉ Q) → σ i = none) ∧
  -- 2. Participants in some Q ∈ Qs have a share.
  (∀ Q ∈ Qs, ∀ i ∈ Q, (σ i).isSome) ∧
  -- 3. For each Q ∈ Qs, the sum of shares is S.
  (∀ Q ∈ Qs, (∑ i : Fin n, if i ∈ Q then ((σ i).getD 0) else 0) = S)

/--
Generate shares for a secret S using random values ρ.
For each Q ∈ Qs, we use the max element to balance the sum.
-/
noncomputable def GenerateShares (Qs : Set (Set (Fin n))) (S : ZMod p) (ρ : Fin n → ZMod p) : Fin n → Share p := fun i =>
  if h : ∃ Q ∈ Qs, i ∈ Q then
    let Q := Classical.choose h
    have hQ_spec : Q ∈ Qs ∧ i ∈ Q := Classical.choose_spec h
    have h_finite : Q.Finite := Set.toFinite Q
    let Q_finset := h_finite.toFinset
    have h_nonempty : Q_finset.Nonempty := by
      rw [Set.Finite.toFinset_nonempty]
      exact ⟨i, hQ_spec.2⟩
    let last := Q_finset.max' h_nonempty
    if i = last then
      -- Sum of random values assigned to other members of Q
      let others := Q_finset.erase last
      let sum_others := ∑ j ∈ others, ρ j
      some (S - sum_others)
    else
      some (ρ i)
  else
    none

/--
Reconstruct the secret from a set of participants G and their shares.
If G contains a qualified set Q, we sum the shares of Q.
-/
noncomputable def ReconstructSecret (Qs : Set (Set (Fin n))) (shares : Fin n → Share p) (G : Set (Fin n)) : Option (ZMod p) :=
  if h : ∃ Q ∈ Qs, Q ⊆ G then
    let Q := Classical.choose h
    -- We sum the shares of members of Q.
    -- We assume shares are present (if not, getD 0 will return 0, which might be wrong, but for valid shares it's fine).
    let sum_shares := ∑ i ∈ (Set.toFinite Q).toFinset, (shares i).getD 0
    some sum_shares
  else
    none

/-
Definition of pivot: selects an element in Q \ A to adjust if the last element is in A.
-/
noncomputable def pivot (Q : Set (Fin n)) (A : Set (Fin n)) : Option (Fin n) :=
  if hQ : Q.Nonempty then
    let last := (Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr hQ)
    if last ∈ A then
      if h_diff : ∃ x, x ∈ Q ∧ x ∉ A then
        some (Classical.choose h_diff)
      else
        none
    else
      none
  else
    none

/-
Definition of shift: the adjustment vector for the random tape.
-/
noncomputable def shift (Qs : Set (Set (Fin n))) (A : Set (Fin n)) (S1 S2 : ZMod p) (i : Fin n) : ZMod p :=
--  S2 - S1
  if _h : ∃ Q ∈ Qs, pivot Q A = some i then
    S2 - S1
  else
    0

/-
Lemma: pivot returns some value iff the last element of Q is in A.
-/
theorem pivot_spec {Q : Set (Fin n)} {A : Set (Fin n)} (hQ : Q.Nonempty) (h_unauth : ¬(Q ⊆ A)) :
  (pivot Q A).isSome ↔ ((Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr hQ)) ∈ A := by
    unfold pivot;
    split_ifs <;> simp_all +decide [ Set.subset_def ]

/-
Lemma: if pivot returns x, then x is in Q, not in A, and not the last element.
-/
theorem pivot_mem {Q : Set (Fin n)} {A : Set (Fin n)} (hQ : Q.Nonempty) (x : Fin n) :
  pivot Q A = some x → x ∈ Q ∧ x ∉ A ∧ x ≠ (Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr hQ) := by
    intros hx;
    unfold pivot at hx;
    split_ifs at hx ; 
    · simp_all [ Finset.max'_eq_sup' ];
      · have := Classical.choose_spec ‹∃ x ∈ Q, x∉A›; 
        aesop;
    · grind

/-
Lemma: The shift vector is zero for any participant in the unauthorized set A.
-/
theorem shift_eq_zero_on_A {Qs : Set (Set (Fin n))} {A : Set (Fin n)} {S1 S2 : ZMod p}
    (_h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (i : Fin n) (hi : i ∈ A) :
    shift Qs A S1 S2 i = 0 := by
  unfold shift
  
  split_ifs with h
  · obtain ⟨Q, hQ, h_pivot⟩ := h
    -- pivot Q A = some i implies i ∉ A
    have := pivot_mem (h_nonempty Q hQ) i h_pivot
    have hi_not_A := this.2.1
    contradiction
  · rfl

/-
Lemma: For a qualified set Q where the last element is in A, the sum of shifts on the other elements is S2 - S1.
-/
theorem sum_shift_eq_diff {Qs : Set (Set (Fin n))} {A : Set (Fin n)} {S1 S2 : ZMod p}
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (h_unauth : ∀ Q ∈ Qs, ¬(Q ⊆ A))
    (Q : Set (Fin n)) (hQ : Q ∈ Qs)
    (last : Fin n) (h_last : last = (Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr (h_nonempty Q hQ)))
    (h_last_in_A : last ∈ A) :
    ∑ j ∈ (Set.toFinite Q).toFinset.erase last, shift Qs A S1 S2 j = S2 - S1 := by
  -- The sum has only one non-zero term, corresponding to the pivot.
  -- pivot Q A is some x, with x ∈ Q \ A.
  -- Since last ∈ A, x ≠ last.
  -- So x ∈ (Q \ {last}).
  -- Also shift is zero everywhere else in Q (because Qs are disjoint).
  have h_shift_def : ∀ j ∈ (Set.toFinite Q).toFinset.erase last, shift Qs A S1 S2 j = if pivot Q A = some j then S2 - S1 else 0 := by
    intro j hj;
    convert if_congr ?_ rfl rfl;
    constructor;
    · rintro ⟨ Q', hQ', h ⟩;
      have h_eq : Q' = Q := by
        have h_eq : j ∈ Q' ∧ j ∈ Q := by
          have := pivot_mem ( h_nonempty Q' hQ' ) j h; aesop;
        have := h_disjoint hQ' hQ;
        exact Classical.not_not.1 fun h => Set.disjoint_left.mp ( this h ) h_eq.1 h_eq.2;
      aesop;
    · exact fun h => ⟨ Q, hQ, h ⟩;
  have h_pivot_def : ∃ x, pivot Q A = some x ∧ x ∈ (Set.toFinite Q).toFinset.erase last := by
    unfold pivot;
    simp_all +decide [ Set.not_subset ];
    exact ⟨ fun h => Classical.choose_spec ( h_unauth Q hQ ) |>.2 <| h ▸ h_last_in_A, Classical.choose_spec ( h_unauth Q hQ ) |>.1 ⟩;
  obtain ⟨ x, hx₁, hx₂ ⟩ := h_pivot_def;
  rw [ Finset.sum_eq_single x ] <;> aesop

/-
Lemma: shift(S2, S1) is the negation of shift(S1, S2).
-/
theorem shift_symm {Qs : Set (Set (Fin n))} {A : Set (Fin n)} {S1 S2 : ZMod p} :
    shift Qs A S2 S1 = - shift Qs A S1 S2 := by
      -- By definition of shift, we have that shift Qs A S2 S1 i = S2 - S1 if there exists a Q in Qs such that pivot Q A is some i, otherwise 0.
      funext i; simp [shift];
      split_ifs <;> ring

/-
Lemma: The generated shares for S2 using the shifted random tape are the same as for S1 using the original tape, for participants in A.
-/
theorem generateShares_shift_eq {Qs : Set (Set (Fin n))} {A : Set (Fin n)} {S1 S2 : ZMod p}
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (h_unauth : ∀ Q ∈ Qs, ¬(Q ⊆ A))
    (ρ : Fin n → ZMod p)
    (i : Fin n) (hi : i ∈ A) :
    GenerateShares Qs S2 (ρ + shift Qs A S1 S2) i = 
    GenerateShares Qs S1 ρ i := by
  -- By definition of GenerateShares, we need to consider three cases: when Q contains i, when Q does not contain i, and when Q is not in Qs.
  by_cases hQ : ∃ Q ∈ Qs, i ∈ Q;
  · -- Since $i \in A$, we have $shift Qs A S1 S2 i = 0$ by definition of shift.
    have h_shift_zero : shift Qs A S1 S2 i = 0 := by
      exact shift_eq_zero_on_A h_disjoint h_nonempty i hi;
    -- Since $shift Qs A S1 S2 i = 0$, adding it to $\rho$ does not change the value.
    simp [h_shift_zero, GenerateShares];
    split_ifs <;> simp [ Finset.sum_add_distrib ];
    convert sum_shift_eq_diff h_disjoint h_nonempty h_unauth _ _ _ rfl using 1;
    rotate_left;
    · exact p;
    · exact ⟨ Fact.out ⟩;
    · exact S1;
    · exact S2;
    · exact Classical.choose hQ;
    · exact Classical.choose_spec hQ |>.1;
    simp +decide [ ← ‹i = _›];
    grind +ring;
  · -- Since there's no Q in Qs containing i, by definition of GenerateShares, both shares should be none. So, the equality holds trivially because both sides are none.
    simp [GenerateShares, hQ]



/-
Lemma: The shift map is a bijection.
-/
theorem shift_is_bijection {Qs : Set (Set (Fin n))} {A : Set (Fin n)} {S1 S2 : ZMod p}
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (h_unauth : ∀ Q ∈ Qs, ¬(Q ⊆ A))
    (shares_A : ∀ i : Fin n, i ∈ A → Share p) :
    Set.BijOn (fun ρ => ρ + shift Qs A S1 S2)
      {ρ | ∀ (i : Fin n) (hi : i ∈ A), GenerateShares Qs S1 ρ i = shares_A i hi}
      {ρ | ∀ (i : Fin n) (hi : i ∈ A), GenerateShares Qs S2 ρ i = shares_A i hi} := by
        refine' ⟨ fun ρ hρ i hi => _, _, _ ⟩;
        · convert generateShares_shift_eq h_disjoint h_nonempty h_unauth ρ i hi using 1;
          exact hρ i hi ▸ rfl;
        · exact fun x hx y hy hxy => by simpa using hxy;
        · intro ρ hρ;
          refine' ⟨ ρ - shift Qs A S1 S2, _, _ ⟩ <;> simp_all +decide [ sub_eq_add_neg ];
          convert generateShares_shift_eq h_disjoint h_nonempty h_unauth ( ρ + -shift Qs A S1 S2 ) using 1;
          rotate_left;
          · exact S1;
          · exact S2;
          · simp +decide [ ← hρ ];
            rw [ eq_comm ]

/-
Perfect security theorem: The number of random tapes consistent with a given set of shares on an unauthorized set is independent of the secret.
-/
theorem PerfectSecurity {n : ℕ} {p : ℕ} [Fact p.Prime]
    (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (A : Set (Fin n))
    (h_unauth : ∀ Q ∈ Qs, ¬(Q ⊆ A)) -- A is unauthorized
    (shares_A : ∀ i : Fin n, i ∈ A → Share p) -- Fixed shares for A
    (S1 S2 : ZMod p) :
    Set.ncard {ρ | ∀ (i : Fin n) (hi : i ∈ A), GenerateShares Qs S1 ρ i = shares_A i hi} =
    Set.ncard {ρ | ∀ (i : Fin n) (hi : i ∈ A), GenerateShares Qs S2 ρ i = shares_A i hi} := by
      -- By Lemma 25, the shift map is a bijection.
      have h_bijection : Set.BijOn (fun ρ => ρ + shift Qs A S1 S2)
        {ρ : Fin n → ZMod p | ∀ i hi, GenerateShares Qs S1 ρ i = shares_A i hi}
        {ρ : Fin n → ZMod p | ∀ i hi, GenerateShares Qs S2 ρ i = shares_A i hi} := by
          exact shift_is_bijection h_disjoint h_nonempty h_unauth shares_A
      rw [ Set.ncard_def, Set.ncard_def, Set.encard_congr ( h_bijection.equiv ) ]

/-
Perfect security theorem: The number of random tapes consistent with a given set of shares on an unauthorized set is independent of the secret.
-/
theorem PerfectSecurity_thm {n : ℕ} {p : ℕ} [Fact p.Prime]
    (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (A : Set (Fin n))
    (h_unauth : ∀ Q ∈ Qs, ¬(Q ⊆ A)) -- A is unauthorized
    (shares_A : ∀ i : Fin n, i ∈ A → Share p) -- Fixed shares for A
    (S1 S2 : ZMod p) :
    Set.ncard {ρ | ∀ (i : Fin n) (hi : i ∈ A), GenerateShares Qs S1 ρ i = shares_A i hi} =
    Set.ncard {ρ | ∀ (i : Fin n) (hi : i ∈ A), GenerateShares Qs S2 ρ i = shares_A i hi} := by
  have h_bij := shift_is_bijection h_disjoint h_nonempty h_unauth shares_A (S1 := S1) (S2 := S2)
  rw [← h_bij.image_eq]
  rw [Set.ncard_image_of_injOn h_bij.injOn]

/-
Helper lemma: The qualified set chosen by GenerateShares is the correct one due to disjointness.
-/
theorem GenerateShares_Q_eq {n : ℕ} {Qs : Set (Set (Fin n))}
    (h_disjoint : Qs.PairwiseDisjoint id)
    {Q : Set (Fin n)} (hQ : Q ∈ Qs)
    {i : Fin n} (hi : i ∈ Q) :
    Classical.choose (show ∃ Q' ∈ Qs, i ∈ Q' from ⟨Q, hQ, hi⟩) = Q := by
  let P := fun Q' => Q' ∈ Qs ∧ i ∈ Q'
  let Q' := Classical.choose (show ∃ Q' ∈ Qs, i ∈ Q' from ⟨Q, hQ, hi⟩)
  have hQ' : Q' ∈ Qs ∧ i ∈ Q' := Classical.choose_spec (show ∃ Q' ∈ Qs, i ∈ Q' from ⟨Q, hQ, hi⟩)
  have h_inter : i ∈ Q' ∩ Q := ⟨hQ'.2, hi⟩
  have h_not_disjoint : ¬Disjoint Q' Q := Set.not_disjoint_iff.mpr ⟨i, h_inter⟩
  by_contra h_ne
  have h_disj := h_disjoint hQ'.1 hQ h_ne
  contradiction

theorem GenerateShares_isValid' {n : ℕ} {p : ℕ} [Fact p.Prime]
    (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (S : ZMod p) (ρ : Fin n → ZMod p) :
    IsValidSharing Qs S (GenerateShares Qs S ρ) := by
  
  refine ⟨?h1, ?h2, ?h3⟩
  /- 1) Participants not in any Q ∈ Qs get `none`. -/
  · intro i hi
    -- hi : (∀ Q ∈ Qs, i ∉ Q)
    have hneg : ¬ (∃ Q ∈ Qs, i ∈ Q) := by
      intro hex
      rcases hex with ⟨Q, hQ, hiQ⟩
      exact (hi Q hQ) hiQ
    -- Now unfold and take the `else` branch
    simp [GenerateShares, hneg]
  /- 2) Participants in a qualified set get `some _` (i.e. `.isSome`). -/
  · intro Q hQ i hiQ
    have hex : ∃ Q' ∈ Qs, i ∈ Q' := ⟨Q, hQ, hiQ⟩
    simp [GenerateShares, hex]
    split_ifs <;> simp
  /- 3) For each Q ∈ Qs, the sum over Q of shares equals S. -/
  · intro Q hQ
    have h_sum : ∑ i ∈ Finset.univ.filter (fun i => i ∈ Q), (GenerateShares Qs S ρ i).getD 0 = S := by
      unfold GenerateShares;
      -- Let's simplify the expression by separating the sum into two parts: the sum over the last element and the sum over the rest.
      have h_split_sum : ∑ i ∈ Finset.univ.filter (fun i => i ∈ Q), (if i = (Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr (h_nonempty Q hQ)) then S - ∑ j ∈ (Set.toFinite Q).toFinset.erase ((Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr (h_nonempty Q hQ))), ρ j else ρ i) = S := by
        simp +decide [ Finset.sum_ite, Finset.filter_ne', Finset.filter_eq' ];
        split_ifs <;> simp_all +decide [ Finset.max'_mem ];
        · ring!;
        · exact False.elim <| ‹¬_› <| Finset.mem_filter.mp ( Finset.max'_mem ( Finset.filter ( fun x => Q x ) Finset.univ ) ⟨ Classical.choose ( h_nonempty Q hQ ), Finset.mem_filter.mpr ⟨ Finset.mem_univ _, Classical.choose_spec ( h_nonempty Q hQ ) ⟩ ⟩ ) |>.2;
      -- By definition of `GenerateShares`, the sum of the shares over Q is equal to the sum in `h_split_sum`.
      convert h_split_sum using 1;
      refine' Finset.sum_congr rfl fun i hi => _;
      have h_eq : Classical.choose (show ∃ Q' ∈ Qs, i ∈ Q' from ⟨Q, hQ, by simpa using hi⟩) = Q := by
                                      exact GenerateShares_Q_eq h_disjoint hQ ( by simpa using hi );
      grind;
    simpa [ Finset.sum_ite ] using h_sum


/-
Proof that the generated shares form a valid sharing.
-/
theorem GenerateShares_isValid {n : ℕ} {p : ℕ} [Fact p.Prime]
    (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (S : ZMod p) (ρ : Fin n → ZMod p) :
    IsValidSharing Qs S (GenerateShares Qs S ρ) := by
  -- To prove the validity of the shares, we need to show that the sum of the shares in any Q in Qs equals S.
  have h_sum_shares : ∀ Q ∈ Qs, (∑ i : Fin n, if i ∈ Q then ((GenerateShares Qs S ρ i).getD 0) else 0) = S := by
    intro Q hQ;
    -- By definition of `GenerateShares`, we know that the sum of the shares in $Q$ is equal to $S$.
    have h_sum : ∑ i ∈ (Set.toFinite Q).toFinset, (if i = (Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr (h_nonempty Q hQ)) then S - ∑ j ∈ (Set.toFinite Q).toFinset.erase ((Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr (h_nonempty Q hQ))), ρ j else ρ i) = S := by
      simp [ Finset.sum_ite, Finset.filter_ne', Finset.filter_eq' ];
      rw [ if_pos ];
      · rw [ Finset.card_eq_one.mpr ] ; 
        · aesop;
        · exact ⟨ _, rfl ⟩;
      · convert Finset.max'_mem _ _;
        any_goals exact Finset.univ.filter fun x => Q x;
        all_goals try infer_instance;
        · grind
        exact Exists.elim ( h_nonempty Q hQ ) fun x hx => ⟨ x, by simpa using hx ⟩;
    -- Since the shares generated by `GenerateShares` are equal to the shares in `h_sum` for each `i` in `Q`, the sums are equal.
    have h_eq_shares : ∀ i ∈ Q, Option.getD (GenerateShares Qs S ρ i) 0 = if i = (Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr (h_nonempty Q hQ)) then S - ∑ j ∈ (Set.toFinite Q).toFinset.erase ((Set.toFinite Q).toFinset.max' ((Set.toFinite Q).toFinset_nonempty.mpr (h_nonempty Q hQ))), ρ j else ρ i := by
      unfold GenerateShares;
      intro i hi
      by_cases h : ∃ Q' ∈ Qs, i ∈ Q';
      · have h_eq_Q : Classical.choose h = Q := by
          exact GenerateShares_Q_eq h_disjoint hQ hi;
        simp [ h_eq_Q ];
        split_ifs <;> simp +decide [ * ];
      · exact False.elim <| h ⟨ Q, hQ, hi ⟩;
    simp_all +decide [ Finset.sum_ite ];
    convert h_sum using 1;
  refine' ⟨ _, _, h_sum_shares ⟩;
  · -- 
    unfold GenerateShares; 
    intro i a
    simp_all only [Set.Finite.toFinset_setOf, dite_eq_right_iff, isEmpty_Prop, not_exists, not_and, not_false_eq_true,
      implies_true, IsEmpty.forall_iff]
  · --
    unfold GenerateShares; 
    intro Q a i a_1
    simp_all only [Set.Finite.toFinset_setOf]
    split
    next h =>
      obtain ⟨w, h⟩ := h
      obtain ⟨left, right⟩ := h
      split
      next h => simp_all only [Option.isSome_some]
      next h => simp_all only [Option.isSome_some]
    next h => simp_all only [not_exists, not_and, Option.isSome_none, Bool.false_eq_true]



/-
Correctness of reconstruction: if G contains a qualified set, it recovers S.
-/
theorem ReconstructSecret_correct {n : ℕ} {p : ℕ} [Fact p.Prime]
    (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (S : ZMod p) (ρ : Fin n → ZMod p)
    (G : Set (Fin n))
    (hG : ∃ Q ∈ Qs, Q ⊆ G) :
    ReconstructSecret Qs (GenerateShares Qs S ρ) G = some S := by
  unfold ReconstructSecret;
  have := Classical.choose_spec hG;
  have h_sum_shares : ∑ i ∈ (Set.toFinite (Classical.choose hG)).toFinset, (GenerateShares Qs S ρ i).getD 0 = S := by
    have h_valid : IsValidSharing Qs S (GenerateShares Qs S ρ) := by
      exact GenerateShares_isValid Qs h_disjoint h_nonempty S ρ
    convert h_valid.2.2 _ this.1 using 1;
    rw [ ← Finset.sum_filter ] ; congr ; ext ; aesop;
  aesop


open AccessStructure SecretSharingScheme 

-- We define the specific Access Structure for Disjoint Sets
def DisjointAS (Qs : Set (Set (Fin n))) : AccessStructure n where
  auth := {A | ∃ Q ∈ Qs, Q ⊆ A}
  h_monotone := by
    intro A B hA hsub
    obtain ⟨Q, hQ, hQA⟩ := hA
    use Q, hQ
    exact Set.Subset.trans hQA hsub


noncomputable def DisjointScheme {n : ℕ} (p : ℕ)
    [Fact p.Prime] (Qs : Set (Set (Fin n)))
    : SecretSharingScheme n := {
  Secret := ZMod p
  Random := Fin n → ZMod p
  Share := fun _ => Option (ZMod p)
  dealer := fun s ρ i => GenerateShares Qs s ρ i
  hSecret_card := by
    simpa using Nat.Prime.two_le Fact.out
  μ := PMF.uniformOfFintype (Fin n → ZMod p)
}

noncomputable def DisjointReconstruction {n : ℕ} (p : ℕ) [Fact p.Prime] (Qs : Set (Set (Fin n))) : 
  ReconstructionAlgorithm (DisjointScheme p Qs) (DisjointAS Qs) := 
  fun B _hB shares => 
    let full_shares : Fin n → Option (ZMod p) := fun i =>
      if h : i ∈ B then shares ⟨i, h⟩ else none
    match ReconstructSecret Qs full_shares B with
    | some s => s
    | none   => (0 : ZMod p)

theorem DisjointScheme_Correctness {n : ℕ} (p : ℕ) [Fact p.Prime] (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty) :
    Correctness (DisjointScheme p Qs) (DisjointAS Qs) (DisjointReconstruction p Qs) := by
  intro s r B hB
  simp [DisjointReconstruction, shares_of_set, DisjointScheme]
  -- We need to handle the type mismatch between the abstract `shares` 
  -- and the concrete `GenerateShares`.
  -- The `shares` passed to `recon` is `fun i => GenerateShares Qs s r i`.
  -- `DisjointReconstruction` converts this to `full_shares`.
  -- We need to show `full_shares` behaves like `GenerateShares` on `B`.
  -- And since `B` contains a qualified set, `ReconstructSecret` should work.
  have h_recon := ReconstructSecret_correct Qs h_disjoint h_nonempty s r B hB
  -- The `ReconstructSecret` in `DisjointReconstruction` uses `full_shares`.
  -- We need to show that `ReconstructSecret` with `full_shares` returns `some s`.
  convert congr_arg Option.get! h_recon using 1;
  unfold ReconstructSecret;
  split_ifs <;> 
  simp --  [ *, Finset.sum_ite ];
  · exact Finset.sum_congr rfl fun x hx => by rw [ if_pos ( by exact Classical.choose_spec ( ‹∃ Q ∈ Qs, Q ⊆ B› ) |>.2 ( by simpa using hx ) ) ] ;
  · rfl


/-
Perfect security theorem: The number of random tapes consistent with a given set of shares on an unauthorized set is independent of the secret.
-/
theorem PerfectSecurity_card_eq {n : ℕ} {p : ℕ} [Fact p.Prime]
    (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty)
    (A : Set (Fin n))
    (h_unauth : ∀ Q ∈ Qs, ¬(Q ⊆ A)) -- A is unauthorized
    (shares_A : ∀ i : Fin n, i ∈ A → Share p) -- Fixed shares for A
    (S1 S2 : ZMod p) :
    Set.ncard {ρ | ∀ (i : Fin n) (hi : i ∈ A), GenerateShares Qs S1 ρ i = shares_A i hi} =
    Set.ncard {ρ | ∀ (i : Fin n) (hi : i ∈ A), GenerateShares Qs S2 ρ i = shares_A i hi} := by
  have h_bij := shift_is_bijection h_disjoint h_nonempty h_unauth shares_A (S1 := S1) (S2 := S2)
  rw [← h_bij.image_eq]
  rw [Set.ncard_image_of_injOn h_bij.injOn]


theorem DisjointScheme_Security {n : ℕ} (p : ℕ) [Fact p.Prime] (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty) :
    PerfectSecurity (DisjointScheme p Qs) (DisjointAS Qs) := by
  unfold SecretSharingScheme.PerfectSecurity DisjointScheme DisjointAS;
  intro B hB s s';
  ext x;
  have h_card : Set.ncard {ρ : Fin n → ZMod p | shares_of_set (DisjointScheme p Qs) s ρ B = x} = Set.ncard {ρ : Fin n → ZMod p | shares_of_set (DisjointScheme p Qs) s' ρ B = x} := by
    have := PerfectSecurity_card_eq Qs h_disjoint h_nonempty B (by
    exact fun Q hQ hQB => hB ⟨ Q, hQ, hQB ⟩) (fun i hi => x ⟨i, hi⟩) s s';
    convert this using 1;
    · congr with ρ ; simp +decide [ funext_iff, shares_of_set ];
      rfl;
    · congr with ρ ; simp +decide [ funext_iff, shares_of_set ];
      rfl;
  simp_all [ Set.ncard_eq_toFinset_card', tsum_fintype ];
  simp_all [ eq_comm, Finset.sum_ite ];
  convert congr_arg ( · * ( p ^ n : ENNReal ) ⁻¹ ) ( congr_arg ( fun x : ℕ => ( x : ENNReal ) ) h_card ) 
  -- using 1


noncomputable def DisjointRealizedScheme {n : ℕ} (p : ℕ) [Fact p.Prime] (Qs : Set (Set (Fin n)))
    (h_disjoint : Qs.PairwiseDisjoint id)
    (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty) :
    RealizedSecretSharingScheme n (DisjointAS Qs) := {
  toSecretSharingScheme := DisjointScheme p Qs
  recon := DisjointReconstruction p Qs
  h_correctness := DisjointScheme_Correctness p Qs h_disjoint h_nonempty
  h_security := DisjointScheme_Security p Qs h_disjoint h_nonempty
}

-- noncomputable def DisjointRealizedScheme {n : ℕ} (p : ℕ) [Fact p.Prime]
--     (Qs : Set (Set (Fin n)))
--     (h_disjoint : Qs.PairwiseDisjoint id)
--     (h_nonempty : ∀ Q ∈ Qs, Q.Nonempty) :
--     RealizedSecretSharingScheme n (DisjointAS Qs) :=
-- RealizedSecretSharingScheme.mk
--   (DisjointScheme p Qs)
--   (DisjointReconstruction p Qs)
--   (DisjointScheme_Correctness p Qs h_disjoint h_nonempty)
--   (DisjointScheme_Security p Qs h_disjoint h_nonempty)


end DisjointAccessStructure




section DistributedHierarchy

open AccessStructure SecretSharingScheme

/-!
### Abstract Distributed Matrix Multiplication Protocol
This structure defines the interface and correctness condition for any
distributed matrix multiplication scheme, independent of how it is implemented.
-/
structure DistributedMatrixMultiplication (n : ℕ) (Γ : AccessStructure n) (F : Type*) [Field F] where
  -- Types
  Secret : Type*
  Share : Fin n → Type*
  Random : Type* -- We need Randomness for LSSS compatibility
  
  -- Protocol Functions
  encode : Secret → Random → (i : Fin n) → Share i
  worker_compute : {d : ℕ} → (i : Fin n) → (Fin d → Share i) → (Fin d → F) → Share i
  reconstruct : (B : Set (Fin n)) → (hB : B ∈ Γ.auth) → ((i : B) → Share i) → Secret

  -- Algebraic Structure needed
  [secret_add : AddCommMonoid Secret]
  [secret_module : Module F Secret]

  -- **RENAMED FIELD** to avoid collision with LSSS.h_correctness
  h_distributed_correctness : 
    ∀ {d : ℕ} (A : Fin d → Secret) (K : Fin d → Random) (x : Fin d → F) 
      (B : Set (Fin n)) (hB : B ∈ Γ.auth),
    let shares (j : Fin d) (i : Fin n) := encode (A j) (K j) i
    let responses (i : B) := worker_compute i (fun j => shares j i) x
    reconstruct B hB responses = ∑ j, x j • A j

/-!
### The Linear Secret Sharing Scheme (LSSS)
This is the cryptographic primitive.
-/
structure LinearSecretSharingScheme (n : ℕ) (Γ : AccessStructure n) (F : Type*) [Field F]
    extends RealizedSecretSharingScheme n Γ where
  
  -- Algebraic Structures
  [secret_add : AddCommMonoid Secret]
  [random_add : AddCommMonoid Random]
  [share_add : ∀ i, AddCommMonoid (Share i)]
  
  [secret_module : Module F Secret]
  [random_module : Module F Random]
  [share_module : ∀ i, Module F (Share i)]
  
  -- Linearity of Dealer
  dealer_linear : (Secret × Random) →ₗ[F] (Π i, Share i)
  h_dealer_eq : ∀ s r, dealer_linear (s, r) = dealer s r

  -- Linearity of Reconstruction
  recon_linear : ∀ (B : Set (Fin n)) (_hB : B ∈ Γ.auth),
    ((i : B) → Share i) →ₗ[F] Secret
  h_recon_eq : ∀ (B : Set (Fin n)) (hB : B ∈ Γ.auth) (shares : (i : B) → Share i),
    recon_linear B hB shares = recon B hB shares

end DistributedHierarchy



namespace LinearSecretSharingScheme

open AccessStructure SecretSharingScheme LinearSecretSharingScheme

  -- Register instances
attribute [instance] secret_add random_add share_add
attribute [instance] secret_module random_module share_module

variable {n : ℕ} {Γ : AccessStructure n} {F : Type*} [Field F]
variable (L : LinearSecretSharingScheme n Γ F)

-- Definition of the Worker's Computation
def worker_compute_impl {d : ℕ} (i : Fin n) (shares : Fin d → L.Share i) (x : Fin d → F) : L.Share i :=
  ∑ j, x j • shares j

-- Definition of Target and Keys (Helpers for the proof)
def target_computation {d : ℕ} (A : Fin d → L.Secret) (x : Fin d → F) : L.Secret :=
  ∑ j, x j • A j

def aggregate_key {d : ℕ} (K : Fin d → L.Random) (x : Fin d → F) : L.Random :=
  ∑ j, x j • K j

-- lemma used in the Homomorphism Lemma
lemma sum_prod_smul
    {n : ℕ} {Γ : AccessStructure n} {F : Type*} [Field F]
    (L : LinearSecretSharingScheme n Γ F)
    {d : ℕ}
    (x : Fin d → F)
    (A : Fin d → L.Secret)
    (K : Fin d → L.Random) :
    ∑ j, x j • (A j, K j) = (∑ j, x j • A j, ∑ j, x j • K j) := by
  ext
  · simp only [Prod.fst_sum, Prod.smul_mk]
  · simp only [Prod.snd_sum, Prod.smul_mk]


-- The Homomorphism Lemma
lemma worker_homomorphism
    {d : ℕ} (A : Fin d → L.Secret) (K : Fin d → L.Random) (x : Fin d → F) (i : Fin n) :
    L.worker_compute_impl i (fun j => L.dealer (A j) (K j) i) x = 
    L.dealer (target_computation L A x) (aggregate_key L K x) i := by
  
  let Ψ := L.dealer_linear
  calc worker_compute_impl L i (fun j => L.dealer (A j) (K j) i) x 
    -- 1. Definition of worker_compute
    = ∑ j, x j • L.dealer (A j) (K j) i := rfl
    
    -- 2. Convert L.dealer to Ψ (the LinearMap) inside the sum
    _ = ∑ j, x j • (Ψ (A j, K j) i) := by
      apply Finset.sum_congr rfl
      intro j _
      rw [← h_dealer_eq] -- Use the consistency property

    -- 3. Pull the evaluation 'i' outside the scalar multiplication
    -- (c • f) i = c • (f i)
    _ = ∑ j, (x j • Ψ (A j, K j)) i := rfl

    -- 4. Pull the evaluation 'i' outside the sum
    -- (∑ f) i = ∑ (f i)
    _ = (∑ j, x j • Ψ (A j, K j)) i := by
      rw [Finset.sum_apply]

    -- 5. Use Linearity of Ψ: ∑ c • Ψ(v) = Ψ(∑ c • v)
    _ = (Ψ (∑ j, x j • (A j, K j))) i := by
      rw [map_sum]
      -- Move scalar multiplication inside the map
      simp_rw [map_smul]

    -- 6. Combine the arguments inside the pair
    -- ∑ (x • A, x • K) = (∑ x A, ∑ x K)
    _ = (Ψ (∑ j, x j • A j, ∑ j, x j • K j)) i := by
      rw [sum_prod_smul]    

    -- 7. Convert back to definitions of target_computation and aggregate_key
    _ = Ψ (target_computation L A x, aggregate_key L K x) i := rfl

    -- 8. Convert back to L.dealer
    _ = L.dealer (target_computation L A x) (aggregate_key L K x) i := by
      rw [h_dealer_eq]

-- The Main Theorem (Correctness)
theorem distributed_computing_correctness
    {d : ℕ} (A : Fin d → L.Secret) (K : Fin d → L.Random) (x : Fin d → F)
    (B : Set (Fin n)) (hB : B ∈ Γ.auth) :
    let worker_responses (i : B) := L.worker_compute_impl i (fun j => L.dealer (A j) (K j) i) x
    L.recon B hB worker_responses = target_computation L A x := by
  
  have h_valid_shares : (fun i : B => L.worker_compute_impl i (fun j => L.dealer (A j) (K j) i) x) =
      shares_of_set L.toSecretSharingScheme (target_computation L A x) (aggregate_key L K x) B := by
    ext i
    apply worker_homomorphism
  
  rw [h_valid_shares]
  exact L.h_correctness (target_computation L A x) (aggregate_key L K x) B hB


structure SecureDistributedMatrixMultiplication (n : ℕ) (Γ : AccessStructure n) (F : Type*) [Field F]
    extends LinearSecretSharingScheme n Γ F where
  /--
  Construct the DistributedMatrixMultiplication instance using the
  definitions and theorems from the LinearSecretSharingScheme namespace.
  -/
  toDistMatrixMul : DistributedMatrixMultiplication n Γ F := {
    Secret := Secret
    Share := Share
    Random := Random
    
    -- Map LSSS functions to Protocol functions
    encode := dealer
    reconstruct := recon
    worker_compute := fun i shares x => worker_compute_impl toLinearSecretSharingScheme i shares x
    
    -- Instances
    secret_add := secret_add
    secret_module := secret_module
    
    -- **Proof of correctness**: We simply call the theorem we proved above.
    h_distributed_correctness := by
      intros d A K x B hB
      apply distributed_computing_correctness toLinearSecretSharingScheme
  }

end LinearSecretSharingScheme

end -- noncomputable 
