import Mathlib.Tactic

set_option linter.style.longLine false



/-
Definition of Access Structure.
Suppose there are n participants, represented by the term
0, 1,..., n-1 in `Fin n`

An access structure consists of a set of subsets of of `{0,1,...,n-1}`
and a proof that this set of sets is satisfies the monotone property.
-/
noncomputable section AccessStructure

structure AccessStructure (n : ℕ) where
  auth : Set (Set (Fin n))
  h_monotone : ∀ {A B}, A ∈ auth → A ⊆ B → B ∈ auth

namespace AccessStructure

/-
Unauthorized sets is the complement of authorized sets.
-/
def unauthorized {n : ℕ} (Γ : AccessStructure n) : Set (Set (Fin n)) :=
  {A | A ∉ Γ.auth}

/-
A set `A` is a minimal authorized set if it is authorized
and no proper subset of `A` is authorized.
-/
def isMinimalAuthorized {n : ℕ} (Γ : AccessStructure n)
    (A : Set (Fin n)) : Prop :=
  A ∈ Γ.auth ∧ ∀ B : Set (Fin n), B ⊂ A → B ∉ Γ.auth

/-
The family Γ₀ of minimal authorized sets.
-/
def minimalAuthorized {n : ℕ} (Γ : AccessStructure n)
    : Set (Set (Fin n)) :=
  {A | isMinimalAuthorized Γ A}

/-
Every authorized set contains a minimal authorized subset.
-/
theorem auth_contains_minimal_auth {n : ℕ} (Γ : AccessStructure n) :
  ∀ B ∈ Γ.auth, ∃ A ∈ Γ.auth, isMinimalAuthorized Γ A ∧ A ⊆ B := by
    intro B hB;
    -- Apply the well-ordering principle to the set of authorized subsets of $B$.
    obtain ⟨A, hA⟩ : ∃ A ∈ {C : Set (Fin n) | C ∈ Γ.auth ∧ C ⊆ B}, ∀ C ∈ {C : Set (Fin n) | C ∈ Γ.auth ∧ C ⊆ B}, A.ncard ≤ C.ncard := by
      apply_rules [ Set.exists_min_image ];
      · exact Set.toFinite _;
      · exact ⟨ B, hB, Set.Subset.refl _ ⟩;
    use A;
    simp_all  [ isMinimalAuthorized ];
    intro C hC hC';
    have := hA.2 C hC' ( hC.1.trans hA.1.2 );
    exact this.not_gt ( Set.ncard_lt_ncard hC )

/-
A set `A` is a maximally unauthorized set if it is unauthorized and any proper superset of `A` is authorized.
-/
def isMaximallyUnauthorized {n : ℕ} (Γ : AccessStructure n)
    (A : Set (Fin n)) : Prop :=
  A ∉ Γ.auth ∧ ∀ B : Set (Fin n), A ⊂ B → B ∈ Γ.auth

/-
The family of maximally unauthorized sets.
-/
def maximallyUnauthorized {n : ℕ} (Γ : AccessStructure n)
    : Set (Set (Fin n)) :=
  {A | isMaximallyUnauthorized Γ A}

/-
The access structure generated by a collection of sets S consists of all supersets of the sets in S.
-/
def generatedAccessStructure {n : ℕ} (S : Set (Set (Fin n)))
   : Set (Set (Fin n)) :=
  upperClosure S

/-
An explicit statement of what `upper close` means.
-/
theorem mem_generatedAccessStructure_iff {n : ℕ} (S : Set (Set (Fin n))) (A : Set (Fin n)) :
    A ∈ generatedAccessStructure S ↔ ∃ B ∈ S, B ⊆ A := by
  simp [generatedAccessStructure, mem_upperClosure]

/-
The generated access structure contains the original collection of sets.
-/
theorem generatedAccessStructure_extensive {n : ℕ} (S : Set (Set (Fin n))) :
    S ⊆ generatedAccessStructure S := by
  exact fun x hx => ⟨ x, hx, le_rfl ⟩

/-
If S ⊆ T, then the access structure generated by T contains the subsets in the access structure generated by S.
-/
theorem generatedAccessStructure_mono {n : ℕ} {S T : Set (Set (Fin n))} (h : S ⊆ T) :
    generatedAccessStructure S ⊆ generatedAccessStructure T := by
  intros A hA
  obtain ⟨B, hB₁, hB₂⟩ := mem_upperClosure.mp hA
  have hB₃ : B ∈ T := h hB₁
  exact mem_upperClosure.mpr ⟨B, hB₃, hB₂⟩

/-
The generated access structure operation is idempotent.
-/
theorem generatedAccessStructure_idempotent {n : ℕ} (S : Set (Set (Fin n))) :
    generatedAccessStructure (generatedAccessStructure S) = generatedAccessStructure S := by
  simp_all [generatedAccessStructure ]

/-
The generated access structure operation is a closure operator.
-/
def generatedAccessStructureClosure (n : ℕ) : ClosureOperator (Set (Set (Fin n))) where
  toFun := generatedAccessStructure
  monotone' := fun _ _ h => generatedAccessStructure_mono h
  le_closure' := generatedAccessStructure_extensive
  idempotent' := generatedAccessStructure_idempotent

/-
The threshold access structure with threshold `t` out of `n` participants.
-/
def thresholdAccessStructure (n t : ℕ) : AccessStructure n where
  auth := generatedAccessStructure {A | A.ncard = t}
  h_monotone := by
    unfold generatedAccessStructure;
    simp [ upperClosure ];
    exact fun { A B } x hx hx' hx'' => ⟨ x, hx, hx'.trans hx'' ⟩

/-
A set is authorized in the threshold access structure iff its size is at least `t`.
-/
theorem threshold_auth_iff (n t : ℕ) (A : Set (Fin n)) :
  A ∈ (thresholdAccessStructure n t).auth ↔ t ≤ A.ncard := by
    constructor;
    · intro hA;
      -- Since $A$ is in the upper closure of the set of subsets
      -- with cardinality $t$, there exists some $B$ with $|B| = t$
      -- such that $B \subseteq A$.
      obtain ⟨B, hB_card, hB_subset⟩ : ∃ B : Set (Fin n), B.ncard = t ∧ B ⊆ A := by
        exact hA;
      exact hB_card ▸ Set.ncard_le_ncard hB_subset;
    · intro ht
      obtain ⟨B, hB⟩ : ∃ B : Set (Fin n), B ⊆ A ∧ B.ncard = t := by
        exact Set.exists_subset_card_eq ht;
      exact ⟨ B, hB.2, hB.1 ⟩


/-
All subsets of size t-1 are maximal unauthorized sets.
-/
theorem threshold_maximalUnauthorized_eq (n t : ℕ) (h_t : t > 0) (h_t_le_n : t ≤ n) :
  (thresholdAccessStructure n t).maximallyUnauthorized = {A | A.ncard = t - 1} := by
    ext A;
    constructor <;> intro hA;
    · have h_card : A.ncard < t := by
        exact lt_of_not_ge fun h => hA.1 <| by exact ( threshold_auth_iff n t A ) |>.2 h;
      have h_card : ∀ B : Set (Fin n), A ⊂ B → t ≤ B.ncard := by
        exact fun B hB => by have := hA.2 B hB; exact (threshold_auth_iff n t B).mp this;
      contrapose! h_card;
      -- Since $A$ is not maximal unauthorized, there exists an element $x \in \{0, 1, ..., n-1\} \setminus A$.
      obtain ⟨x, hx⟩ : ∃ x : Fin n, x ∉ A := by
        by_cases hA_univ : A = Set.univ;
        · simp_all  [ Set.ncard_univ ];
          linarith;
        · exact Set.nonempty_compl.2 hA_univ;
      refine' ⟨ Insert.insert x A, _, _ ⟩ <;> simp_all ;
      · exact ⟨ Set.subset_insert _ _, fun h => hx <| h <| Set.mem_insert _ _ ⟩;
      · rw [ Set.ncard_insert_of_notMem hx ] ; omega;
    · constructor;
      · exact fun h => by have := threshold_auth_iff n t A |>.1 h; linarith [ hA.symm, Nat.sub_add_cancel h_t ] ;
      · intro B hB
        have hB_card : B.ncard ≥ t := by
          have := Set.ncard_lt_ncard hB;
          grind;
        exact threshold_auth_iff n t B |>.2 hB_card

/-
The minimal authorized sets of the threshold access structure are exactly the sets of size `t`.
-/
theorem threshold_minimalAuthorized_eq (n t : ℕ) :
  (thresholdAccessStructure n t).minimalAuthorized = {A | A.ncard = t} := by
    -- To prove equality of sets, we show each set is a subset of the other.
    apply Set.ext
    intro A
    simp [minimalAuthorized, thresholdAccessStructure];
    constructor;
    · rintro ⟨ hA₁, hA₂ ⟩;
      obtain ⟨ B, hB₁, hB₂ ⟩ := hA₁;
      contrapose! hA₂;
      refine' ⟨ B, _, _ ⟩;
      · exact lt_of_le_of_ne hB₂ fun h => hA₂ <| h ▸ hB₁;
      · exact ⟨ B, hB₁, Set.Subset.refl _ ⟩;
    · intro hA
      constructor
      · exact (by
        exact ⟨ A, hA, Set.Subset.refl _ ⟩)
      · -- If B is a proper subset of A, then its cardinality is strictly less than t.
        intro B hB
        have hB_card : B.ncard < t := by
          exact hA ▸ Set.ncard_lt_ncard hB;
        simp [generatedAccessStructure];
        exact fun x hx hx' => hB_card.not_ge <| hx ▸ Set.ncard_le_ncard hx'

end AccessStructure  -- namespace

end AccessStructure  -- section
